[workspace]
members = [
    "crates/*",
    "libs/*"
]
resolver = "2"


[workspace.package]
version = "0.0.1"
rust-version = "1.80"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["ybiao"]
repository = "https://github.com/lagudomeze/ioc"