[package]
name = "modb"
version = "0.0.0"
edition = "2021"

[dependencies]
modc = { path = "../modc" }


[build-dependencies]
prebuilds = { path = "../../libs/prebuilds" }
print = { path = "../../libs/print" }

[package.metadata.bootstrap_items]
print = "print"