[package]
name = "moda"
version = "0.0.0"
edition = "2021"

[dependencies]

[build-dependencies]
cargo_metadata = "0.18.1"
print = { path = "../../libs/print" }
boot_build = { path = "../../../ioc/libs/boot_build" }