[package]
name = "moda"
version = "0.0.0"
edition = "2021"

[dependencies]
modb = { path = "../modb" }
sss = { path = "../modc", package = "modc" }
bootstrap = { path = "../../libs/bootstrap" }
print = { path = "../../libs/print" }

[package.metadata.bootstrap_items]
print = "print"